// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgreSQLconnect;

#nullable disable

namespace PostgreSQLconnect.Migrations
{
	[DbContext(typeof(ApplicationDBContext))]
	[Migration("20211228145513_transferingDB")]
	partial class transferingDB
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.1")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

			modelBuilder.Entity("Entities.ProductEntity", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

					b.Property<string>("Nome")
						.HasColumnType("text");

					b.Property<string>("Senha")
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("Product");
				});
#pragma warning restore 612, 618
		}
	}
}
